branches:
  - main
  - fix-release-cicd
major_on_zero: false
commit_parser: angular
commit_parser_options:
  allowed_tags:
    - build
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - style
    - refactor
    - test
  minor_tags:
    - feat
  patch_tags:
    - fix
    - perf
changelog:
  template_dir: templates
  changelog_file: CHANGELOG.md
  exclude_commit_patterns:
    - "^chore\\(release\\):"